import {test,expect} from '@playwright/test'
import sharp from 'sharp'
test('triagem contextual, menu no tablet e confirmação sem redirecionamento',async({page})=>{
 await page.addInitScript(()=>localStorage.setItem('vr_cookie_consent','acknowledged'))
 const errors:string[]=[];page.on('pageerror',error=>errors.push(error.message))
 await page.emulateMedia({reducedMotion:'reduce'})
 await page.setViewportSize({width:1024,height:768});await page.goto('/')
 const trigger=page.getByRole('button',{name:'Abrir menu',exact:true})
 await trigger.click();await expect(page.getByRole('navigation',{name:'Navegação no celular'})).toBeVisible()
 await page.keyboard.press('Escape');await expect(trigger).toBeFocused()
 await expect(page.getByRole('navigation',{name:'Navegação no celular'})).toHaveCount(0)
 expect(await page.locator('a button, button a').count()).toBe(0)
 for(const type of ['EMPRESA','TRABALHADOR','CONTA']){
  const service=page.locator('#como-ajudar a[href*="atendimento='+type+'"]')
  await expect(service).toHaveCount(1);await service.click()
  await expect(page).toHaveURL(new RegExp('atendimento='+type+'#contato'))
  await expect(page.getByLabel('Tipo de Atendimento')).toHaveValue(type)
 }
 await page.getByLabel('Seu Nome Completo').fill('Contato visual de teste')
 await page.getByLabel('Número do WhatsApp (com DDD)').fill('11999999999')
 await page.getByLabel('Concordo com o tratamento').check()
 await page.getByRole('button',{name:'Enviar e Iniciar Atendimento'}).click()
 await expect(page.getByRole('status')).toContainText('Informações enviadas com sucesso!')
 await expect(page).toHaveURL(/atendimento=CONTA#contato/)
 await expect(page.getByRole('link',{name:'Abrir conversa no WhatsApp'})).toHaveCount(0)
 await page.getByRole('button',{name:'Enviar outro contato'}).click()
 await expect(page.getByLabel('Seu Nome Completo')).toHaveValue('')
 expect(errors).toEqual([])
})
test('site público, menu móvel e páginas adicionais',async({page})=>{
 for(const url of ['/','/recuperacao-de-instagram','/blog','/politica-de-privacidade','/termos-de-uso']){const response=await page.goto(url);expect(response?.status()).toBe(200);await expect(page.locator('h1')).toBeVisible()}
 await page.setViewportSize({width:390,height:844});await page.goto('/');await page.getByRole('button',{name:'Abrir menu',exact:true}).click();await expect(page.getByRole('button',{name:'Fechar menu',exact:true})).toBeVisible()
 expect(await page.evaluate(()=>document.documentElement.scrollWidth<=window.innerWidth)).toBe(true)
})
test('autenticação, proteção, CRUD e revogação da sessão',async({page,request,playwright})=>{
 const unauthorized=await request.get('/api/admin/cms/faq');expect(unauthorized.status()).toBe(401)
 await page.goto('/admin');await expect(page).toHaveURL(/\/admin\/login/)
 await page.getByLabel(/E-mail/i).fill('test@example.com');await page.getByLabel(/^Senha/).fill('incorrect-password');await page.getByRole('button',{name:/Entrar/}).click();await expect(page.getByText('Credenciais inválidas.')).toBeVisible()
 await page.getByLabel(/^Senha/).fill('Test-only-password-42!');await page.getByRole('button',{name:/Entrar/}).click();await expect(page).toHaveURL(/\/admin$/)
 const headers={origin:'http://localhost:3100'}
 const csrf=await page.request.post('/api/admin/cms/faq',{data:{data:{}}});expect(csrf.status()).toBe(403)
 const created=await page.request.post('/api/admin/cms/faq',{headers,data:{data:{question:'Pergunta de teste',answer:'Resposta inicial',category:'geral',active:true}}});expect(created.ok()).toBe(true);const {record}=await created.json()
 const updated=await page.request.post('/api/admin/cms/faq',{headers,data:{id:record.id,data:{question:'Pergunta de teste',answer:'Resposta atualizada',category:'geral',active:true}}});expect(updated.ok()).toBe(true)
 await page.goto('/');await expect(page.getByRole('button',{name:/Pergunta de teste/})).toBeVisible()
 const faqList=await (await page.request.get('/api/admin/cms/faq')).json();const ids=faqList.records.map((r:{id:string})=>r.id).reverse()
 const ordered=await page.request.put('/api/admin/cms/faq/order',{headers,data:{ids}});expect(ordered.ok()).toBe(true)
 expect((await (await page.request.get('/api/admin/cms/faq')).json()).records.map((r:{id:string})=>r.id)).toEqual(ids)
 const removed=await page.request.delete('/api/admin/cms/faq',{headers,data:{id:record.id}});expect(removed.ok()).toBe(true)
 await page.goto('/admin/blog');await expect(page.getByRole('heading',{name:'Blog e artigos'})).toBeVisible()
 await page.getByRole('button',{name:'Novo registro'}).click()
 await page.getByLabel('Título *',{exact:true}).fill('Artigo de teste')
 await page.getByLabel('Resumo *',{exact:true}).fill('Resumo do artigo de teste.')
 await page.getByLabel('Conteúdo *',{exact:true}).fill('Conteúdo informativo de teste.')
 await page.getByRole('button',{name:'Salvar alterações'}).click()
 await expect(page.getByRole('status')).toContainText('Conteúdo salvo')
 const draft=await page.request.get('/blog/artigo-de-teste');expect(draft.status()).toBe(404)
 await page.getByLabel('Situação *',{exact:true}).selectOption('PUBLISHED')
 await page.getByRole('button',{name:'Publicar artigo'}).click()
 await expect(page.getByRole('status')).toContainText('Conteúdo salvo')
 const published=await page.request.get('/blog/artigo-de-teste');expect(published.status()).toBe(200)
 const sitemap=await page.request.get('/sitemap.xml');expect(await sitemap.text()).toContain('/blog/artigo-de-teste')
 await page.goto('/admin/media');await expect(page.getByRole('heading',{name:'Biblioteca de mídia'})).toBeVisible()
 const image=await sharp({create:{width:8,height:8,channels:3,background:'#E2C2A0'}}).png().toBuffer()
 const uploaded=await page.request.post('/api/admin/media',{headers,multipart:{alt:'Imagem de teste',file:{name:'teste.png',mimeType:'image/png',buffer:image}}});expect(uploaded.ok()).toBe(true)
 const media=await uploaded.json();expect(media.record.mimeType).toBe('image/webp')
 expect((await page.request.delete('/api/admin/media',{headers,data:{id:media.record.id}})).ok()).toBe(true)
 const settings=await (await page.request.get('/api/admin/settings')).json()
 expect((await page.request.put('/api/admin/settings',{headers,data:{...Object.fromEntries(Object.entries(settings.settings).filter(([key])=>!['id','updatedAt'].includes(key))),whatsapp:'5511999999999'}})).ok()).toBe(true)
 const click=await page.request.get('/api/whatsapp?phone=5511999999999&message=Teste&type=CONTA',{maxRedirects:0});expect(click.status()).toBe(302);expect(click.headers().location).toContain('https://wa.me/5511999999999')
 const editorCreated=await page.request.post('/api/admin/security',{headers,data:{action:'create-user',name:'Editor de teste',email:'editor@example.com',password:'Editor-test-password-42!',role:'EDITOR'}});expect(editorCreated.ok()).toBe(true)
 const editorContext=await playwright.request.newContext({baseURL:'http://localhost:3100'})
 expect((await editorContext.post('/api/auth/login',{headers,data:{email:'editor@example.com',password:'Editor-test-password-42!'}})).ok()).toBe(true)
 expect((await editorContext.get('/api/admin/leads')).status()).toBe(403)
 expect((await editorContext.get('/api/admin/cms/settings')).status()).toBe(403)
 expect((await editorContext.get('/api/admin/cms/blog')).ok()).toBe(true)
 await editorContext.dispose()
 const security=await page.request.get('/api/admin/security');const {currentSession}=await security.json()
 await page.request.post('/api/admin/security',{headers,data:{action:'revoke',id:currentSession}})
 const revoked=await page.request.get('/api/admin/cms/faq');expect(revoked.status()).toBe(401)
})
test('triagem exige LGPD e persiste o contato',async({request})=>{
 const headers={origin:'http://localhost:3100'};const input={name:'Contato de teste',whatsapp:'11999999999',type:'CONTA',message:'Minha conta foi suspensa.',consent:true,website_url:''}
 expect((await request.post('/api/contact',{headers,data:{...input,consent:false}})).status()).toBe(400)
 const res=await request.post('/api/contact',{headers,data:input});expect(res.ok()).toBe(true);expect((await res.json()).leadId).toBeTruthy()
})
