'use client'
import {useRouter} from 'next/navigation'
import {useState,useEffect,useCallback} from 'react'
type User={id:string;name:string;email:string;role:string}
type Data={user:User;sessions:{id:string;createdAt:string;expiresAt:string;ip:string;userAgent:string}[];users:User[];logs:{id:string;createdAt:string;action:string;entity:string;user:{name:string}}[];currentSession:string}
export function SecurityPanel({admin}:{admin:boolean}){
 const router=useRouter()
 const [data,setData]=useState<Data|null>(null);const [message,setMessage]=useState('');const [busy,setBusy]=useState(false)
 const load=useCallback(async()=>{const res=await fetch('/api/admin/security');const json=await res.json();if(!res.ok)throw new Error(json.error);setData(json)},[])
 useEffect(()=>{const timer=setTimeout(()=>{void load().catch(e=>setMessage(e.message))},0);return()=>clearTimeout(timer)},[load])
 async function mutate(input:object){setBusy(true);try{const res=await fetch('/api/admin/security',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(input)});const json=await res.json();if(!res.ok)throw new Error(json.error);await load();setMessage('Alteração salva.')}catch(e){setMessage(e instanceof Error?e.message:'Erro na operação.')}finally{setBusy(false)}}
 if(!data)return <p role="status">{message || 'Carregando segurança…'}</p>
 return <div className="cms space-y-8"><h1 className="heading-serif text-3xl">Usuários e segurança</h1>{message && <p role="status" className="text-accent">{message}</p>}<form className="cms-panel space-y-4" onSubmit={e=>{e.preventDefault();const form=new FormData(e.currentTarget);const password=String(form.get('password') || '');void mutate({action:'profile',name:form.get('name'),email:form.get('email'),currentPassword:form.get('currentPassword'),...(password?{password}:{})})}}><h2 className="heading-serif text-2xl">Meu perfil</h2><label className="block">Nome<input name="name" defaultValue={data.user.name} required/></label><label className="block">E-mail<input name="email" type="email" defaultValue={data.user.email} required/></label><label className="block">Senha atual<input name="currentPassword" type="password" autoComplete="current-password" required/></label><label className="block">Nova senha (opcional, mínimo 12 caracteres)<input name="password" type="password" minLength={12} autoComplete="new-password"/></label><button disabled={busy} className="cms-primary">Salvar perfil</button></form>
 <section className="cms-panel space-y-4"><h2 className="heading-serif text-2xl">Minhas sessões</h2>{data.sessions.map(s=><div key={s.id} className="flex flex-wrap gap-3 justify-between border-t border-white/10 pt-4"><div><p className="text-sm">{s.userAgent || 'Navegador não informado'}</p><p className="text-xs text-text-secondary">{s.ip} · expira {new Date(s.expiresAt).toLocaleString('pt-BR')}{s.id===data.currentSession?' · sessão atual':''}</p></div><button disabled={busy} onClick={()=>{if(s.id===data.currentSession){fetch('/api/auth/logout',{method:'POST'}).then(()=>router.push('/admin/login'))}else void mutate({action:'revoke',id:s.id})}}>Encerrar</button></div>)}</section>
 {admin && <><form className="cms-panel space-y-4" onSubmit={e=>{e.preventDefault();void mutate({action:'create-user',...Object.fromEntries(new FormData(e.currentTarget))})}}><h2 className="heading-serif text-2xl">Criar usuário</h2><label className="block">Nome<input name="name" required/></label><label className="block">E-mail<input name="email" type="email" required/></label><label className="block">Senha inicial<input name="password" type="password" minLength={12} required autoComplete="new-password"/></label><label className="block">Perfil<select name="role"><option value="EDITOR">Editor (conteúdo)</option><option value="ADMIN">Administrador</option></select></label><button disabled={busy} className="cms-primary">Criar usuário</button></form><section className="cms-panel space-y-4"><h2 className="heading-serif text-2xl">Usuários cadastrados</h2>{data.users.map(u=><div key={u.id} className="flex flex-wrap gap-3 justify-between"><p>{u.name} · {u.email} · {u.role}</p>{u.id!==data.user.id && <button disabled={busy} onClick={()=>mutate({action:'role',id:u.id,role:u.role==='ADMIN'?'EDITOR':'ADMIN'})}>Alterar para {u.role==='ADMIN'?'editor':'administrador'}</button>}</div>)}</section><section className="cms-panel space-y-3"><h2 className="heading-serif text-2xl">Últimas alterações</h2>{data.logs.map(l=><p key={l.id} className="text-sm text-text-secondary">{new Date(l.createdAt).toLocaleString('pt-BR')} · {l.user.name} · {l.action} · {l.entity}</p>)}</section></>}
 </div>
}
